### PR TITLE
New Word Beer'o clock added

### PR DESCRIPTION
**Pull request by narendra36**
:)

### CODE REVIEW

**Comment by narendra36** [comment]
@sukhbir-singh Plz resolves conflicts by yourself and merge this pull request :smile:

**Comment by sukhbir-singh** [comment]
haha!! please resolve next time by yourself...

**Comment by narendra36** [comment]
Oh! I see you just merged it.

**Comment by narendra36** [comment]
I'm too lazy to pull on local PC and commit all that stuff I just wanted to do it online only on GitHub itself. :smiley:

**Pull request merged**
